#-----------------------------------------------------------------#
# Fig. 5E. Broad data-driven screening of eight two-function triad sets
#
# This script replaces fixed set blueprints with a broader screening process.
# It starts from the complete ranked triad table generated by the expanded
# Fig. 5E workflow and selects eight six-triad figures.
#
# Each figure contains:
#   - two functional groups
#   - three triads per functional group
#   - a 3-column x 2-row layout
#
# Screening priorities:
#   A. data reliability: three-edge correlation strength/significance,
#      three-way direction consistency, node-direction coherence, prevalence
#   B. functional relevance to CRC prognosis and anticancer-treatment biology
#   C. reported/curatable relevance of the microorganism to CRC, treatment
#      outcome, or health-associated intestinal ecology
#   D. current biological interest in the microorganism/metabolite
#
# Biological-prior ordering follows:
#   functional/therapy relevance > microorganism relevance >= current interest
#
# The biological priors are used for ranking, not as causal evidence.
# The resulting networks remain hypothesis-generating association triads.
#-----------------------------------------------------------------#

rm(list = ls())
options(stringsAsFactors = FALSE)
setwd('D:/2-연구/2-CRC metagenomics/')

for (pkg in c('dplyr', 'stringr', 'ggplot2', 'readr', 'tibble', 'tidyr', 'purrr', 'scales', 'svglite')) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    install.packages(pkg, type = 'binary')
  }
}

suppressPackageStartupMessages({
  library(dplyr)
  library(stringr)
  library(ggplot2)
  library(readr)
  library(tibble)
  library(tidyr)
  library(purrr)
  library(scales)
  library(grid)
})

#-----------------------------------------------------------------#
# 0. User-adjustable settings
#-----------------------------------------------------------------#
analysis_set <- 'before'
selected_set_n <- 8L
triads_per_functional_group <- 3L
functional_groups_per_set <- 2L
exclude_existing_curated_bile_six <- TRUE

# Candidate-level reliability requirements.
minimum_three_way_consistency <- 2L
minimum_node_direction_matches <- 2L
minimum_nominally_significant_edges <- 1L
minimum_p10_edges <- 2L

# Diversity controls used in the first two selection passes.
maximum_sets_per_metabolite_family_strict <- 2L
maximum_sets_per_metabolite_program_strict <- 1L
maximum_sets_per_metabolite_family_relaxed <- 3L
maximum_sets_per_metabolite_program_relaxed <- 2L

# A group must be capable of producing three distinct triads.
minimum_group_candidates <- 3L
minimum_group_unique_genes <- 3L
minimum_group_unique_species_gene_pairs <- 3L

#-----------------------------------------------------------------#
# 1. Input
#-----------------------------------------------------------------#
ranked_candidate_file <- paste0(
  'host_RNAseq/results_clean_metabolite_host/Figure5_host_RNAseq/tables/',
  'Fig5E_expanded_integrated_all_ranked_triads_', analysis_set, '.csv'
)

if (!file.exists(ranked_candidate_file)) {
  stop('The complete ranked-candidate table was not found: ', ranked_candidate_file, call. = FALSE)
}

ranked_candidates <- read.csv(
  ranked_candidate_file,
  check.names = FALSE,
  stringsAsFactors = FALSE
)

required_columns <- c(
  'Species', 'Metabolite', 'Gene',
  'species_met_r', 'species_met_p',
  'met_gene_r', 'met_gene_p',
  'species_gene_r', 'species_gene_p',
  'species_effect', 'metabolite_effect', 'gene_effect',
  'triad_confidence_score', 'final_gene_function_category',
  'metabolite_family', 'metabolite_program'
)

missing_columns <- setdiff(required_columns, colnames(ranked_candidates))
if (length(missing_columns) > 0) {
  stop(
    'The ranked-candidate table is missing required columns: ',
    paste(missing_columns, collapse = ', '),
    call. = FALSE
  )
}

for (column_i in c(
  'quality_tier', 'n_edges_p05', 'n_edges_p10',
  'three_way_consistency_count', 'node_direction_match_count',
  'mean_abs_correlation', 'correlation_geometric_mean_p',
  'species_prevalence', 'metabolite_prevalence',
  'total_reference_support_score', 'final_gene_relevance_pass'
)) {
  if (!column_i %in% colnames(ranked_candidates)) ranked_candidates[[column_i]] <- NA
}

safe_rescale <- function(x) {
  x <- suppressWarnings(as.numeric(x))
  finite_x <- x[is.finite(x)]
  if (length(finite_x) == 0) return(rep(0, length(x)))
  if (length(unique(finite_x)) == 1) {
    out <- rep(0.5, length(x))
    out[!is.finite(x)] <- 0
    return(out)
  }
  out <- scales::rescale(x, to = c(0, 1), from = range(finite_x, na.rm = TRUE))
  out[!is.finite(out)] <- 0
  out
}

ranked_candidates <- ranked_candidates %>%
  mutate(
    quality_tier = coalesce(suppressWarnings(as.integer(quality_tier)), 5L),
    n_edges_p05 = coalesce(suppressWarnings(as.integer(n_edges_p05)), 0L),
    n_edges_p10 = coalesce(suppressWarnings(as.integer(n_edges_p10)), 0L),
    three_way_consistency_count = coalesce(
      suppressWarnings(as.integer(three_way_consistency_count)), 0L
    ),
    node_direction_match_count = coalesce(
      suppressWarnings(as.integer(node_direction_match_count)), 0L
    ),
    mean_abs_correlation = coalesce(
      suppressWarnings(as.numeric(mean_abs_correlation)),
      (abs(species_met_r) + abs(met_gene_r) + abs(species_gene_r)) / 3
    ),
    correlation_geometric_mean_p = coalesce(
      suppressWarnings(as.numeric(correlation_geometric_mean_p)),
      exp(
        (
          log(pmax(species_met_p, .Machine$double.xmin)) +
            log(pmax(met_gene_p, .Machine$double.xmin)) +
            log(pmax(species_gene_p, .Machine$double.xmin))
        ) / 3
      )
    ),
    species_prevalence = coalesce(suppressWarnings(as.numeric(species_prevalence)), 0),
    metabolite_prevalence = coalesce(suppressWarnings(as.numeric(metabolite_prevalence)), 0),
    total_reference_support_score = coalesce(
      suppressWarnings(as.numeric(total_reference_support_score)), 0
    ),
    final_gene_relevance_pass = case_when(
      as.character(final_gene_relevance_pass) %in% c('TRUE', 'True', 'true', '1') ~ TRUE,
      as.character(final_gene_relevance_pass) %in% c('FALSE', 'False', 'false', '0') ~ FALSE,
      TRUE ~ final_gene_function_category != 'Other / unassigned'
    ),
    triad_key = paste(Species, Metabolite, Gene, sep = '|||'),
    species_metabolite_key = paste(Species, Metabolite, sep = '|||'),
    species_gene_key = paste(Species, Gene, sep = '|||'),
    metabolite_gene_key = paste(Metabolite, Gene, sep = '|||')
  ) %>%
  filter(
    final_gene_relevance_pass,
    final_gene_function_category != 'Other / unassigned',
    is.finite(triad_confidence_score),
    is.finite(species_met_r),
    is.finite(met_gene_r),
    is.finite(species_gene_r),
    three_way_consistency_count >= minimum_three_way_consistency,
    node_direction_match_count >= minimum_node_direction_matches,
    n_edges_p05 >= minimum_nominally_significant_edges,
    n_edges_p10 >= minimum_p10_edges
  ) %>%
  distinct(triad_key, final_gene_function_category, .keep_all = TRUE)

if (nrow(ranked_candidates) < selected_set_n * 6L) {
  stop('Too few eligible triads remained for eight six-triad figures.', call. = FALSE)
}

#-----------------------------------------------------------------#
# 2. Broad functional, microorganism and interest priors
#-----------------------------------------------------------------#
# These are transparent ranking priors. They should be manually reviewed and
# updated when the literature interpretation changes.
#-----------------------------------------------------------------#
ranked_candidates <- ranked_candidates %>%
  mutate(
    function_macrotheme = case_when(
      final_gene_function_category %in% c(
        'CRC epithelial / Wnt / MYC program',
        'Cell cycle / proliferation',
        'Apoptosis / DNA-damage response',
        'EMT / ECM remodeling / invasion'
      ) ~ 'Tumor-cell response',
      final_gene_function_category %in% c(
        'Innate immune / cytokine signaling',
        'Adaptive / cytotoxic immunity',
        'Immune tolerance / regulatory'
      ) ~ 'Immune response',
      final_gene_function_category %in% c(
        'Barrier / mucus / epithelial junction',
        'AhR / indole / tryptophan response',
        'Bile-acid / xenobiotic signaling',
        'NAD / niacin metabolism',
        'Metabolic remodeling'
      ) ~ 'Metabolite sensing / epithelial response',
      final_gene_function_category %in% c(
        'Hypoxia / oxidative stress / glycolysis',
        'Golgi / endosomal trafficking'
      ) ~ 'Microenvironment / trafficking',
      TRUE ~ 'Other interpretable response'
    ),
    functional_mechanism_score = case_when(
      final_gene_function_category == 'CRC epithelial / Wnt / MYC program' ~ 1.00,
      final_gene_function_category == 'Apoptosis / DNA-damage response' ~ 0.97,
      final_gene_function_category == 'Cell cycle / proliferation' ~ 0.95,
      final_gene_function_category == 'Innate immune / cytokine signaling' ~ 0.93,
      final_gene_function_category == 'Adaptive / cytotoxic immunity' ~ 0.93,
      final_gene_function_category == 'Hypoxia / oxidative stress / glycolysis' ~ 0.90,
      final_gene_function_category == 'EMT / ECM remodeling / invasion' ~ 0.90,
      final_gene_function_category == 'Immune tolerance / regulatory' ~ 0.87,
      final_gene_function_category == 'Barrier / mucus / epithelial junction' ~ 0.84,
      final_gene_function_category == 'Bile-acid / xenobiotic signaling' ~ 0.83,
      final_gene_function_category == 'AhR / indole / tryptophan response' ~ 0.82,
      final_gene_function_category == 'NAD / niacin metabolism' ~ 0.78,
      final_gene_function_category == 'Metabolic remodeling' ~ 0.73,
      final_gene_function_category == 'Golgi / endosomal trafficking' ~ 0.60,
      TRUE ~ 0.55
    ),
    microorganism_relevance_score = case_when(
      str_detect(
        Species,
        regex(
          'Fusobacterium_nucleatum|Peptostreptococcus_anaerobius|Bacteroides_fragilis|Parvimonas_micra|Streptococcus_gallolyticus|Escherichia_coli|Enterococcus_faecalis|Gemella_morbillorum|Solobacterium_moorei|Porphyromonas_asaccharolytica',
          ignore_case = TRUE
        )
      ) ~ 1.00,
      str_detect(
        Species,
        regex(
          'Akkermansia|Faecalibacterium|Roseburia|Anaerobutyricum|Anaerostipes|Coprococcus|Ruminococcus|Bifidobacterium|Intestinimonas|Mediterraneibacter|Butyricicoccus',
          ignore_case = TRUE
        )
      ) ~ 0.86,
      str_detect(
        Species,
        regex('Bacteroides|Phocaeicola|Alistipes|Desulfovibrio|Clostridium', ignore_case = TRUE)
      ) ~ 0.67,
      TRUE ~ 0.48
    ),
    metabolite_attention_score = case_when(
      metabolite_program == 'IPA' ~ 1.00,
      metabolite_program == 'IAA' ~ 0.97,
      metabolite_program == 'ILA' ~ 0.97,
      metabolite_program == 'Secondary bile acids' ~ 0.94,
      metabolite_program == 'Butyrate' ~ 0.94,
      metabolite_program == 'Conjugated bile acids' ~ 0.89,
      metabolite_program == 'Primary bile acids' ~ 0.86,
      metabolite_program == 'Nicotinic acid / niacin' ~ 0.86,
      metabolite_program == 'Other indole / tryptophan' ~ 0.78,
      metabolite_program == 'Other SCFA / organic acids' ~ 0.68,
      TRUE ~ 0.55
    ),
    microorganism_attention_score = case_when(
      str_detect(
        Species,
        regex('Fusobacterium|Akkermansia|Bacteroides_fragilis|Faecalibacterium|Roseburia|Bifidobacterium|Peptostreptococcus_anaerobius', ignore_case = TRUE)
      ) ~ 1.00,
      str_detect(
        Species,
        regex('Coprococcus|Ruminococcus|Anaerobutyricum|Intestinimonas|Desulfovibrio', ignore_case = TRUE)
      ) ~ 0.78,
      TRUE ~ 0.50
    ),
    current_interest_score =
      0.70 * metabolite_attention_score +
      0.30 * microorganism_attention_score
  )

ranked_candidates <- ranked_candidates %>%
  mutate(
    score_confidence = safe_rescale(triad_confidence_score),
    score_correlation_p = safe_rescale(-log10(pmax(correlation_geometric_mean_p, 1e-300))),
    score_correlation_strength = safe_rescale(mean_abs_correlation),
    score_consistency = three_way_consistency_count / 3,
    score_node_direction = node_direction_match_count / 3,
    score_prevalence = 0.5 * safe_rescale(species_prevalence) + 0.5 * safe_rescale(metabolite_prevalence),
    score_reference = safe_rescale(total_reference_support_score),
    data_reliability_score =
      0.30 * score_confidence +
      0.20 * score_correlation_p +
      0.15 * score_correlation_strength +
      0.15 * score_consistency +
      0.12 * score_node_direction +
      0.05 * score_prevalence +
      0.03 * score_reference,
    triad_screen_score = 100 * (
      0.45 * data_reliability_score +
        0.30 * functional_mechanism_score +
        0.15 * microorganism_relevance_score +
        0.10 * current_interest_score
    )
  ) %>%
  arrange(desc(triad_screen_score), quality_tier, correlation_geometric_mean_p)

#-----------------------------------------------------------------#
# 3. Exclude the already curated bile-acid six, when requested
#-----------------------------------------------------------------#
current_curated <- tibble(
  Species = character(), Metabolite = character(), Gene = character(),
  triad_key = character(), species_metabolite_key = character(),
  species_gene_key = character(), metabolite_gene_key = character()
)

current_curated_file <- paste0(
  'host_RNAseq/results_clean_metabolite_host/Figure5_host_RNAseq/tables/',
  'Fig5E_curated_six_bile_acid_triads_', analysis_set, '.csv'
)

if (exclude_existing_curated_bile_six && file.exists(current_curated_file)) {
  current_curated <- read.csv(
    current_curated_file,
    check.names = FALSE,
    stringsAsFactors = FALSE
  ) %>%
    mutate(
      triad_key = paste(Species, Metabolite, Gene, sep = '|||'),
      species_metabolite_key = paste(Species, Metabolite, sep = '|||'),
      species_gene_key = paste(Species, Gene, sep = '|||'),
      metabolite_gene_key = paste(Metabolite, Gene, sep = '|||')
    )
  
  ranked_candidates <- ranked_candidates %>%
    filter(!triad_key %in% current_curated$triad_key)
}

#-----------------------------------------------------------------#
# 4. Screen all metabolite-program/function groups
#-----------------------------------------------------------------#
# Exact-program groups are preferred. Family-level groups are available as
# fallback when one exact program cannot provide three sufficiently diverse
# triads for a functional category.
#-----------------------------------------------------------------#
exact_group_index <- ranked_candidates %>%
  group_by(
    metabolite_family,
    metabolite_program,
    final_gene_function_category,
    function_macrotheme
  ) %>%
  summarise(
    group_resolution = 'exact metabolite program',
    n_candidates = n(),
    n_species = n_distinct(Species),
    n_metabolites = n_distinct(Metabolite),
    n_genes = n_distinct(Gene),
    n_species_gene_pairs = n_distinct(species_gene_key),
    n_species_metabolite_pairs = n_distinct(species_metabolite_key),
    n_metabolite_gene_pairs = n_distinct(metabolite_gene_key),
    top3_mean_screen_score = mean(head(sort(triad_screen_score, decreasing = TRUE), 3)),
    median_screen_score = median(triad_screen_score, na.rm = TRUE),
    maximum_screen_score = max(triad_screen_score, na.rm = TRUE),
    median_confidence_score = median(triad_confidence_score, na.rm = TRUE),
    median_function_score = median(functional_mechanism_score, na.rm = TRUE),
    median_microorganism_score = median(microorganism_relevance_score, na.rm = TRUE),
    median_interest_score = median(current_interest_score, na.rm = TRUE),
    .groups = 'drop'
  ) %>%
  filter(
    n_candidates >= minimum_group_candidates,
    n_genes >= minimum_group_unique_genes,
    n_species_gene_pairs >= minimum_group_unique_species_gene_pairs
  ) %>%
  mutate(
    group_id = paste('program', metabolite_program, final_gene_function_category, sep = '|||'),
    group_label = paste(metabolite_program, final_gene_function_category, sep = ' — '),
    group_diversity_score = pmin(n_species, 6) / 6 + pmin(n_metabolites, 3) / 3,
    group_priority_score =
      0.62 * top3_mean_screen_score +
      0.23 * median_screen_score +
      5 * group_diversity_score +
      3
  )

family_group_index <- ranked_candidates %>%
  group_by(
    metabolite_family,
    final_gene_function_category,
    function_macrotheme
  ) %>%
  summarise(
    metabolite_program = 'Mixed programs',
    group_resolution = 'metabolite family',
    n_candidates = n(),
    n_species = n_distinct(Species),
    n_metabolites = n_distinct(Metabolite),
    n_genes = n_distinct(Gene),
    n_species_gene_pairs = n_distinct(species_gene_key),
    n_species_metabolite_pairs = n_distinct(species_metabolite_key),
    n_metabolite_gene_pairs = n_distinct(metabolite_gene_key),
    top3_mean_screen_score = mean(head(sort(triad_screen_score, decreasing = TRUE), 3)),
    median_screen_score = median(triad_screen_score, na.rm = TRUE),
    maximum_screen_score = max(triad_screen_score, na.rm = TRUE),
    median_confidence_score = median(triad_confidence_score, na.rm = TRUE),
    median_function_score = median(functional_mechanism_score, na.rm = TRUE),
    median_microorganism_score = median(microorganism_relevance_score, na.rm = TRUE),
    median_interest_score = median(current_interest_score, na.rm = TRUE),
    .groups = 'drop'
  ) %>%
  filter(
    n_candidates >= minimum_group_candidates,
    n_genes >= minimum_group_unique_genes,
    n_species_gene_pairs >= minimum_group_unique_species_gene_pairs,
    n_metabolites >= 2
  ) %>%
  mutate(
    group_id = paste('family', metabolite_family, final_gene_function_category, sep = '|||'),
    group_label = paste(metabolite_family, final_gene_function_category, sep = ' — '),
    group_diversity_score = pmin(n_species, 6) / 6 + pmin(n_metabolites, 3) / 3,
    group_priority_score =
      0.62 * top3_mean_screen_score +
      0.23 * median_screen_score +
      5 * group_diversity_score
  )

group_index <- bind_rows(exact_group_index, family_group_index) %>%
  arrange(desc(group_priority_score), desc(top3_mean_screen_score))

if (nrow(group_index) < functional_groups_per_set * selected_set_n) {
  stop('Too few eligible metabolite/function groups were available for broad screening.', call. = FALSE)
}

write.csv(
  group_index,
  paste0(
    'host_RNAseq/results_clean_metabolite_host/Figure5_host_RNAseq/tables/',
    'Fig5E_broad_screen_candidate_group_index_', analysis_set, '.csv'
  ),
  row.names = FALSE
)

#-----------------------------------------------------------------#
# 5. Generate all coherent two-group set candidates
#-----------------------------------------------------------------#
set_candidate_index <- bind_rows(
  lapply(
    utils::combn(seq_len(nrow(group_index)), 2, simplify = FALSE),
    function(pair_i) {
      g1 <- group_index[pair_i[1], , drop = FALSE]
      g2 <- group_index[pair_i[2], , drop = FALSE]
      
      same_program <-
        g1$group_resolution == 'exact metabolite program' &&
        g2$group_resolution == 'exact metabolite program' &&
        g1$metabolite_program == g2$metabolite_program
      same_family <- g1$metabolite_family == g2$metabolite_family
      same_macrotheme <- g1$function_macrotheme == g2$function_macrotheme
      same_function <- g1$final_gene_function_category == g2$final_gene_function_category
      
      # Avoid redundant exact/family representations of the same function.
      nested_duplicate <-
        same_family && same_function &&
        g1$group_resolution != g2$group_resolution
      
      if ((!same_program && !same_family && !same_macrotheme) || nested_duplicate) return(NULL)
      
      relation <- case_when(
        same_program ~ 'same metabolite program',
        same_family ~ 'same metabolite family',
        same_macrotheme ~ 'shared functional macrotheme',
        TRUE ~ 'other'
      )
      
      coherence_bonus <- case_when(
        same_program ~ 12,
        same_family ~ 8,
        same_macrotheme ~ 4,
        TRUE ~ 0
      )
      
      function_diversity_bonus <- ifelse(same_function, 0, 4)
      program_diversity_bonus <- ifelse(g1$metabolite_program != g2$metabolite_program, 2, 0)
      
      title_i <- if (same_program) {
        paste0(
          g1$metabolite_program, '-centered ',
          g1$final_gene_function_category, ' and ',
          g2$final_gene_function_category, ' triads'
        )
      } else if (same_family) {
        paste0(
          g1$metabolite_family, ': ',
          g1$metabolite_program, ' / ', g1$final_gene_function_category,
          ' plus ',
          g2$metabolite_program, ' / ', g2$final_gene_function_category
        )
      } else {
        paste0(
          g1$function_macrotheme, ': ',
          g1$metabolite_program, ' and ', g2$metabolite_program, ' triads'
        )
      }
      
      tibble(
        set_candidate_id = paste(g1$group_id, g2$group_id, sep = '___'),
        group1_id = g1$group_id,
        group2_id = g2$group_id,
        group1_label = g1$group_label,
        group2_label = g2$group_label,
        group1_resolution = g1$group_resolution,
        group2_resolution = g2$group_resolution,
        group1_family = g1$metabolite_family,
        group2_family = g2$metabolite_family,
        group1_program = g1$metabolite_program,
        group2_program = g2$metabolite_program,
        group1_function = g1$final_gene_function_category,
        group2_function = g2$final_gene_function_category,
        group1_macrotheme = g1$function_macrotheme,
        group2_macrotheme = g2$function_macrotheme,
        set_relation = relation,
        set_title = title_i,
        set_priority_score =
          g1$group_priority_score + g2$group_priority_score +
          coherence_bonus + function_diversity_bonus + program_diversity_bonus,
        minimum_group_priority = min(g1$group_priority_score, g2$group_priority_score),
        mean_top3_screen_score = mean(c(g1$top3_mean_screen_score, g2$top3_mean_screen_score))
      )
    }
  )
) %>%
  arrange(desc(set_priority_score), desc(minimum_group_priority), desc(mean_top3_screen_score))

if (nrow(set_candidate_index) == 0) {
  stop('No coherent two-function set candidates were generated.', call. = FALSE)
}

write.csv(
  set_candidate_index,
  paste0(
    'host_RNAseq/results_clean_metabolite_host/Figure5_host_RNAseq/tables/',
    'Fig5E_broad_screen_candidate_set_index_', analysis_set, '.csv'
  ),
  row.names = FALSE
)

#-----------------------------------------------------------------#
# 6. Diversity-aware triad selection within each candidate set
#-----------------------------------------------------------------#
get_group_pool <- function(group_id_i) {
  group_i <- group_index %>% filter(group_id == group_id_i) %>% slice_head(n = 1)
  if (nrow(group_i) == 0) return(ranked_candidates[0, , drop = FALSE])
  
  if (group_i$group_resolution == 'exact metabolite program') {
    ranked_candidates %>%
      filter(
        metabolite_program == group_i$metabolite_program,
        final_gene_function_category == group_i$final_gene_function_category
      )
  } else {
    ranked_candidates %>%
      filter(
        metabolite_family == group_i$metabolite_family,
        final_gene_function_category == group_i$final_gene_function_category
      )
  }
}

global_used <- list(
  triad = unique(current_curated$triad_key),
  species_metabolite = unique(current_curated$species_metabolite_key),
  species_gene = unique(current_curated$species_gene_key),
  metabolite_gene = unique(current_curated$metabolite_gene_key),
  species = unique(current_curated$Species),
  metabolite = unique(current_curated$Metabolite),
  gene = unique(current_curated$Gene)
)

select_three_diverse_triads <- function(candidate_pool, already_selected, global_used) {
  if (nrow(candidate_pool) == 0) return(candidate_pool)
  
  candidate_pool <- candidate_pool %>%
    filter(!triad_key %in% global_used$triad) %>%
    mutate(
      global_reuse_penalty =
        12 * as.integer(species_gene_key %in% global_used$species_gene) +
        8 * as.integer(species_metabolite_key %in% global_used$species_metabolite) +
        7 * as.integer(metabolite_gene_key %in% global_used$metabolite_gene) +
        3 * as.integer(Gene %in% global_used$gene) +
        2 * as.integer(Species %in% global_used$species) +
        1 * as.integer(Metabolite %in% global_used$metabolite),
      selection_score = triad_screen_score - global_reuse_penalty
    ) %>%
    arrange(
      desc(selection_score),
      quality_tier,
      desc(n_edges_p05),
      correlation_geometric_mean_p,
      desc(mean_abs_correlation)
    )
  
  selected <- candidate_pool[0, , drop = FALSE]
  used_species_metabolite <- already_selected$species_metabolite_key
  used_species_gene <- already_selected$species_gene_key
  used_metabolite_gene <- already_selected$metabolite_gene_key
  used_genes <- already_selected$Gene
  used_species <- already_selected$Species
  
  # Pass 1: distinct species, gene and all two-node pairs within the figure.
  for (i in seq_len(nrow(candidate_pool))) {
    candidate_i <- candidate_pool[i, , drop = FALSE]
    if (
      candidate_i$species_metabolite_key %in% used_species_metabolite ||
      candidate_i$species_gene_key %in% used_species_gene ||
      candidate_i$metabolite_gene_key %in% used_metabolite_gene ||
      candidate_i$Gene %in% used_genes ||
      candidate_i$Species %in% used_species
    ) next
    
    selected <- bind_rows(selected, candidate_i)
    used_species_metabolite <- c(used_species_metabolite, candidate_i$species_metabolite_key)
    used_species_gene <- c(used_species_gene, candidate_i$species_gene_key)
    used_metabolite_gene <- c(used_metabolite_gene, candidate_i$metabolite_gene_key)
    used_genes <- c(used_genes, candidate_i$Gene)
    used_species <- c(used_species, candidate_i$Species)
    if (nrow(selected) >= triads_per_functional_group) break
  }
  
  # Pass 2: allow a repeated species, but never repeat a gene or a two-node pair.
  if (nrow(selected) < triads_per_functional_group) {
    for (i in seq_len(nrow(candidate_pool))) {
      candidate_i <- candidate_pool[i, , drop = FALSE]
      if (
        candidate_i$triad_key %in% selected$triad_key ||
        candidate_i$species_metabolite_key %in% used_species_metabolite ||
        candidate_i$species_gene_key %in% used_species_gene ||
        candidate_i$metabolite_gene_key %in% used_metabolite_gene ||
        candidate_i$Gene %in% used_genes
      ) next
      
      selected <- bind_rows(selected, candidate_i)
      used_species_metabolite <- c(used_species_metabolite, candidate_i$species_metabolite_key)
      used_species_gene <- c(used_species_gene, candidate_i$species_gene_key)
      used_metabolite_gene <- c(used_metabolite_gene, candidate_i$metabolite_gene_key)
      used_genes <- c(used_genes, candidate_i$Gene)
      if (nrow(selected) >= triads_per_functional_group) break
    }
  }
  
  selected %>% slice_head(n = triads_per_functional_group)
}

try_build_set <- function(set_row, global_used) {
  group_order <- c(1L, 2L)
  group_ids <- c(set_row$group1_id, set_row$group2_id)
  group_labels <- c(set_row$group1_label, set_row$group2_label)
  selected_in_set <- ranked_candidates[0, , drop = FALSE]
  
  for (group_i in seq_along(group_ids)) {
    selected_group <- select_three_diverse_triads(
      get_group_pool(group_ids[group_i]),
      selected_in_set,
      global_used
    )
    
    if (nrow(selected_group) < triads_per_functional_group) return(NULL)
    
    selected_group <- selected_group %>%
      mutate(
        group_order = group_order[group_i],
        display_group = group_labels[group_i],
        source_group_id = group_ids[group_i]
      )
    
    selected_in_set <- bind_rows(selected_in_set, selected_group)
  }
  
  if (
    nrow(selected_in_set) != 6L ||
    anyDuplicated(selected_in_set$triad_key) > 0 ||
    anyDuplicated(selected_in_set$species_metabolite_key) > 0 ||
    anyDuplicated(selected_in_set$species_gene_key) > 0 ||
    anyDuplicated(selected_in_set$metabolite_gene_key) > 0 ||
    anyDuplicated(selected_in_set$Gene) > 0
  ) return(NULL)
  
  selected_in_set %>%
    arrange(group_order, Metabolite, Species, Gene) %>%
    group_by(group_order, display_group) %>%
    mutate(panel_in_group = row_number()) %>%
    ungroup()
}

selected_set_members_list <- list()
selected_set_index_list <- list()
used_set_candidate_ids <- character()
used_group_ids <- character()
family_set_counts <- integer()
program_set_counts <- integer()

selection_passes <- tribble(
  ~selection_pass, ~max_family_sets, ~max_program_sets, ~allow_group_reuse,
  1L, maximum_sets_per_metabolite_family_strict, maximum_sets_per_metabolite_program_strict, FALSE,
  2L, maximum_sets_per_metabolite_family_relaxed, maximum_sets_per_metabolite_program_relaxed, FALSE,
  3L, 4L, 3L, TRUE
)

for (pass_i in seq_len(nrow(selection_passes))) {
  if (length(selected_set_members_list) >= selected_set_n) break
  
  for (candidate_i in seq_len(nrow(set_candidate_index))) {
    if (length(selected_set_members_list) >= selected_set_n) break
    
    set_row <- set_candidate_index[candidate_i, , drop = FALSE]
    if (set_row$set_candidate_id %in% used_set_candidate_ids) next
    
    if (!selection_passes$allow_group_reuse[pass_i]) {
      if (set_row$group1_id %in% used_group_ids || set_row$group2_id %in% used_group_ids) next
    }
    
    families_i <- unique(c(set_row$group1_family, set_row$group2_family))
    programs_i <- unique(c(set_row$group1_program, set_row$group2_program))
    programs_i <- programs_i[programs_i != 'Mixed programs']
    
    family_limit_exceeded <- any(vapply(
      families_i,
      function(z) {
        current_n <- if (z %in% names(family_set_counts)) family_set_counts[[z]] else 0L
        current_n >= selection_passes$max_family_sets[pass_i]
      },
      logical(1)
    ))
    if (family_limit_exceeded) next
    
    program_limit_exceeded <- any(vapply(
      programs_i,
      function(z) {
        current_n <- if (z %in% names(program_set_counts)) program_set_counts[[z]] else 0L
        current_n >= selection_passes$max_program_sets[pass_i]
      },
      logical(1)
    ))
    if (program_limit_exceeded) next
    
    selected_members_i <- try_build_set(set_row, global_used)
    if (is.null(selected_members_i)) next
    
    set_rank_i <- length(selected_set_members_list) + 1L
    selected_members_i <- selected_members_i %>%
      mutate(
        set_rank = set_rank_i,
        set_candidate_id = set_row$set_candidate_id,
        set_title = set_row$set_title,
        set_relation = set_row$set_relation,
        set_priority_score = set_row$set_priority_score,
        selection_pass = selection_passes$selection_pass[pass_i],
        set_member_rank = row_number()
      )
    
    selected_set_members_list[[set_rank_i]] <- selected_members_i
    selected_set_index_list[[set_rank_i]] <- tibble(
      set_rank = set_rank_i,
      set_candidate_id = set_row$set_candidate_id,
      set_title = set_row$set_title,
      set_relation = set_row$set_relation,
      group1_label = set_row$group1_label,
      group2_label = set_row$group2_label,
      group1_family = set_row$group1_family,
      group2_family = set_row$group2_family,
      group1_program = set_row$group1_program,
      group2_program = set_row$group2_program,
      group1_function = set_row$group1_function,
      group2_function = set_row$group2_function,
      set_priority_score = set_row$set_priority_score,
      selection_pass = selection_passes$selection_pass[pass_i],
      n_species = n_distinct(selected_members_i$Species),
      n_metabolites = n_distinct(selected_members_i$Metabolite),
      n_genes = n_distinct(selected_members_i$Gene),
      median_triad_screen_score = median(selected_members_i$triad_screen_score),
      minimum_triad_screen_score = min(selected_members_i$triad_screen_score)
    )
    
    used_set_candidate_ids <- c(used_set_candidate_ids, set_row$set_candidate_id)
    used_group_ids <- unique(c(used_group_ids, set_row$group1_id, set_row$group2_id))
    
    for (family_i in families_i) {
      current_n <- if (family_i %in% names(family_set_counts)) family_set_counts[[family_i]] else 0L
      family_set_counts[family_i] <- current_n + 1L
    }
    for (program_i in programs_i) {
      current_n <- if (program_i %in% names(program_set_counts)) program_set_counts[[program_i]] else 0L
      program_set_counts[program_i] <- current_n + 1L
    }
    
    global_used$triad <- unique(c(global_used$triad, selected_members_i$triad_key))
    global_used$species_metabolite <- unique(c(global_used$species_metabolite, selected_members_i$species_metabolite_key))
    global_used$species_gene <- unique(c(global_used$species_gene, selected_members_i$species_gene_key))
    global_used$metabolite_gene <- unique(c(global_used$metabolite_gene, selected_members_i$metabolite_gene_key))
    global_used$species <- unique(c(global_used$species, selected_members_i$Species))
    global_used$metabolite <- unique(c(global_used$metabolite, selected_members_i$Metabolite))
    global_used$gene <- unique(c(global_used$gene, selected_members_i$Gene))
  }
}

selected_set_members <- bind_rows(selected_set_members_list)
selected_set_index <- bind_rows(selected_set_index_list)

if (nrow(selected_set_index) != selected_set_n || nrow(selected_set_members) != selected_set_n * 6L) {
  write.csv(
    set_candidate_index,
    paste0(
      'host_RNAseq/results_clean_metabolite_host/Figure5_host_RNAseq/tables/',
      'Fig5E_broad_screen_selection_failure_candidates_', analysis_set, '.csv'
    ),
    row.names = FALSE
  )
  stop(
    'Broad screening generated ', nrow(selected_set_index), ' of ', selected_set_n,
    ' requested sets. Review the candidate-set diagnostic table.',
    call. = FALSE
  )
}

write.csv(
  selected_set_index,
  paste0(
    'host_RNAseq/results_clean_metabolite_host/Figure5_host_RNAseq/tables/',
    'Fig5E_broad_screen_selected_eight_set_index_', analysis_set, '.csv'
  ),
  row.names = FALSE
)
write.csv(
  selected_set_members,
  paste0(
    'host_RNAseq/results_clean_metabolite_host/Figure5_host_RNAseq/tables/',
    'Fig5E_broad_screen_selected_eight_set_members_', analysis_set, '.csv'
  ),
  row.names = FALSE
)

#-----------------------------------------------------------------#
# 7. Plot eight figures: six triads in one horizontal row
#-----------------------------------------------------------------#
group_cols <- c('non_pCR' = '#E07A73', 'pCR' = '#5AB49B')
correlation_cols <- c('negative' = '#3B6EA8', 'zero' = 'grey92', 'positive' = '#B14A4A')

plot_two_function_triad_set <- function(triad_table, output_file, plot_title) {
  if (nrow(triad_table) != 6L) {
    stop('Each figure must contain exactly six triads.', call. = FALSE)
  }
  
  # Fixed display order: functional group -> metabolite -> species -> gene.
  triad_table <- triad_table %>%
    arrange(group_order, Metabolite, Species, Gene) %>%
    group_by(group_order, display_group) %>%
    mutate(panel_in_group = row_number()) %>%
    ungroup() %>%
    mutate(
      panel_number = row_number(),
      panel = factor(
        paste0('#', panel_number),
        levels = paste0('#', seq_len(n()))
      )
    )
  
  triangle_width <- 1.44
  triangle_height <- sqrt(3) / 2 * triangle_width
  
  node_data <- bind_rows(lapply(seq_len(nrow(triad_table)), function(i) {
    tibble(
      panel = triad_table$panel[i],
      x = c(0, triangle_width / 2, triangle_width),
      y = c(0, triangle_height, 0),
      label = c(
        str_replace_all(triad_table$Species[i], '_', ' '),
        str_replace_all(triad_table$Metabolite[i], '_', ' '),
        triad_table$Gene[i]
      ),
      node_effect = c(
        triad_table$species_effect[i],
        triad_table$metabolite_effect[i],
        triad_table$gene_effect[i]
      ),
      label_x = c(-0.04, triangle_width / 2, triangle_width + 0.04),
      label_y = c(-0.16, triangle_height + 0.15, -0.16),
      hjust = c(0, 0.5, 1),
      fontface = c('italic', 'plain', 'bold')
    )
  }))
  
  edge_data <- bind_rows(lapply(seq_len(nrow(triad_table)), function(i) {
    tibble(
      panel = triad_table$panel[i],
      x = c(0, triangle_width / 2, 0),
      y = c(0, triangle_height, 0),
      xend = c(triangle_width / 2, triangle_width, triangle_width),
      yend = c(triangle_height, 0, 0),
      r = c(
        triad_table$species_met_r[i],
        triad_table$met_gene_r[i],
        triad_table$species_gene_r[i]
      ),
      p = c(
        triad_table$species_met_p[i],
        triad_table$met_gene_p[i],
        triad_table$species_gene_p[i]
      ),
      label_x = c(0.28, triangle_width - 0.28, triangle_width / 2),
      label_y = c(0.55 * triangle_height, 0.55 * triangle_height, -0.08)
    )
  })) %>%
    mutate(
      edge_label = paste0(
        'r=', sprintf('%.2f', r),
        case_when(
          p < 0.001 ~ '***',
          p < 0.01 ~ '**',
          p < 0.05 ~ '*',
          TRUE ~ ''
        )
      ),
      edge_linetype = ifelse(p < 0.05, 'solid', 'longdash')
    )
  
  finite_effect <- abs(node_data$node_effect[is.finite(node_data$node_effect)])
  effect_limit <- if (length(finite_effect) == 0) {
    1
  } else {
    max(1, quantile(finite_effect, 0.90, na.rm = TRUE))
  }
  
  node_data <- node_data %>%
    mutate(node_effect_plot = pmax(pmin(node_effect, effect_limit), -effect_limit))
  
  # Print each functional-group label only once, above the middle triad of
  # the corresponding three-triad block. Per-triad score/consistency text is
  # retained in the CSV output but removed from the figure.
  group_header_data <- triad_table %>%
    filter(panel_in_group == 2L) %>%
    transmute(
      panel,
      x = triangle_width / 2,
      y = triangle_height + 0.42,
      label = display_group
    )
  
  p_set <- ggplot() +
    geom_segment(
      data = edge_data,
      aes(
        x = x, y = y, xend = xend, yend = yend,
        color = r, linewidth = abs(r), linetype = edge_linetype
      ),
      lineend = 'round'
    ) +
    geom_text(
      data = edge_data,
      aes(x = label_x, y = label_y, label = edge_label),
      size = 2.35,
      color = 'grey20'
    ) +
    geom_point(
      data = node_data,
      aes(x = x, y = y, fill = node_effect_plot),
      shape = 21,
      size = 5.0,
      color = 'grey30',
      stroke = 0.5
    ) +
    geom_text(
      data = node_data,
      aes(
        x = label_x, y = label_y, label = label,
        hjust = hjust, fontface = fontface
      ),
      size = 2.5,
      color = 'grey15'
    ) +
    geom_text(
      data = group_header_data,
      aes(x = x, y = y, label = label),
      size = 2.3,
      fontface = 'bold',
      color = 'grey15',
      lineheight = 0.90
    ) +
    scale_color_gradient2(
      low = correlation_cols['negative'],
      mid = correlation_cols['zero'],
      high = correlation_cols['positive'],
      midpoint = 0,
      limits = c(-1, 1),
      name = 'Spearman r'
    ) +
    scale_fill_gradient2(
      low = alpha(group_cols['non_pCR'], 0.85),
      mid = 'white',
      high = alpha(group_cols['pCR'], 0.85),
      midpoint = 0,
      limits = c(-effect_limit, effect_limit),
      name = 'Node enrichment\npCR vs non-pCR'
    ) +
    scale_linewidth(range = c(0.55, 1.35), guide = 'none') +
    scale_linetype_identity() +
    coord_equal(
      xlim = c(-0.16, triangle_width + 0.16),
      ylim = c(-0.25, triangle_height + 0.58),
      clip = 'off'
    ) +
    facet_wrap(~ panel, nrow = 1) +
    labs(
      title = plot_title,
      subtitle = '* P<0.05, ** P<0.01, *** P<0.001'
    ) +
    theme_void(base_size = 9) +
    theme(
      strip.text = element_blank(),
      legend.position = 'bottom',
      legend.box = 'horizontal',
      legend.title = element_text(size = 8),
      legend.text = element_text(size = 7.5),
      plot.title = element_text(size = 10.5, face = 'bold'),
      plot.subtitle = element_text(size = 7.8),
      panel.spacing = unit(2.7, 'mm'),
      plot.margin = margin(4, 6, 4, 6)
    )
  
  ggsave(
    output_file,
    p_set,
    width = 17.6,
    height = 3.65,
    device = 'svg'
  )
  
  p_set
}

dir.create(
  'figures/Fig5E_broad_screen_eight_sets_horizontal',
  recursive = TRUE,
  showWarnings = FALSE
)

p_first_broad_set <- NULL
for (set_i in seq_len(selected_set_n)) {
  set_table_i <- selected_set_members %>%
    filter(set_rank == set_i)
  
  set_title_i <- selected_set_index$set_title[
    selected_set_index$set_rank == set_i
  ][1]
  
  file_stub_i <- set_title_i %>%
    str_replace_all('[^A-Za-z0-9]+', '_') %>%
    str_replace_all('_+', '_') %>%
    str_replace_all('^_|_$', '')
  
  p_set_i <- plot_two_function_triad_set(
    set_table_i,
    paste0(
      'figures/Fig5E_broad_screen_eight_sets_horizontal/',
      'Fig5E_broad_set_', sprintf('%02d', set_i), '_',
      file_stub_i, '_', analysis_set, '.svg'
    ),
    paste0('Set ', sprintf('%02d', set_i), '. ', set_title_i)
  )
  
  if (set_i == 1L) {
    p_first_broad_set <- p_set_i
  } else {
    rm(p_set_i)
    invisible(gc())
  }
}

if (!is.null(p_first_broad_set)) print(p_first_broad_set)

save(
  group_index,
  set_candidate_index,
  selected_set_index,
  selected_set_members,
  p_first_broad_set,
  file = paste0(
    'host_RNAseq/results_clean_metabolite_host/Figure5_host_RNAseq/',
    'Fig5E_broad_screen_eight_two_function_sets_horizontal_',
    analysis_set,
    '.RData'
  )
)

message(
  'Completed: ',
  nrow(selected_set_index), ' horizontal figures; ',
  nrow(selected_set_members), ' triads.'
)
